directory: ~/Music/FLAC
library: ~/Music/library.db

import:
  copy: yes
  write: yes
  resume: ask
  detail: yes
  log: beetslog.txt
  languages: en pl

art_filename: cover

match:
  preferred:
    countries: ["US", "GB|UK", "PL"]
    media: ["CD", "Digital Media|File"]
    original_year: yes

plugins:
  - autobpm
  - convert
  - chroma
  - deezer
  # - spotify
  - embedart
  - fetchart
  - info
  - musicbrainz
  - playlist
  - badfiles
  - duplicates
  - lyrics
  # - lastgenre
  - edit
  - replaygain
  - rewrite
  - importadded
  - keyfinder
  - replace
  # - smartplaylist
  # - playlist
  # - extrafiles

paths:
  default: $albumartist/$album%aunique{}%ifdef{disc, (Disc $disc)}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

musicbrainz:
  genres: yes
  extra_tags: [alias, barcode, catalognum, country, label, media, tracks, year]
  external_ids:
    discogs: yes
    bandcamp: yes
    spotify: yes
    deezer: yes
    beatport: yes
    tidal: yes
  ratelimit: 4

convert:
  auto: no
  copy_album_art: yes
  album_art_maxwidth: 600
  dest: ~/Music/MP3
  embed: yes
  format: mp3
  formats:
    mp3:
      command: sh -c 'ffmpeg -i "$1" -y -vn -aq 0 "$2"; beet lyrics -lp "$1" > "${2%.*}.lrc"' -- "$source" "$dest"
    opus:
      command: sh -c 'ffmpeg -i "$1" -y -vn -acodec libopus -ab 128k "$2"; beet lyrics -lp "$1" > "${2%.*}.lrc"' -- "$source" "$dest"
    aac:
      command: sh -c 'ffmpeg -i "$1" -y -vn -acodec aac -aq 0 "$2"; beet lyrics -lp "$1" > "${2%.*}.lrc"' -- "$source" "$dest"
      extension: m4a

replaygain:
  backend: gstreamer

autobpm:
  auto: yes

lyrics:
  auto: yes
  synced: yes

extrafiles:
  patterns:
    all: "*.*"

fetchart:
  high_resolution: yes
  sources:
    - itunes
    - deezer
    - coverart: release
    - coverart: releasegroup
    - filesystem
    - "*"
  store_source: yes

keyfinder:
  bin: keyfinder-cli
